name: CI
on:
  push:

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.12.0
        with:
          enable-cache: 'true'
          refresh-cli: 'false'

      - name: Install dependencies
        run: devbox run -- pnpm install

      - name: Tests
        run: devbox run -- pnpm test

